// backend/utils/github.js
import { Octokit } from "@octokit/rest";
import fs from "fs";
import path from "path";
import { execSync } from "child_process";
import dotenv from "dotenv";

dotenv.config({ path: path.resolve("backend/.env") });

const octokit = new Octokit({ auth: process.env.GIT_TOKEN });
const GIT_USERNAME = process.env.GIT_USERNAME;

export async function createRepo(repoName, description = "Generated site") {
  try {
    const response = await octokit.repos.createForAuthenticatedUser({
      name: repoName,
      description,
      private: false,
      auto_init: true,
    });
    console.log("✅ Repository created:", response.data.html_url);
    return response.data;
  } catch (error) {
    console.error("❌ Failed to create repository:", error.message);
    throw error;
  }
}

export async function enablePages(repoName) {
  try {
    await octokit.repos.createPagesSite({
      owner: GIT_USERNAME,
      repo: repoName,
      build_type: "workflow",
    });
    console.log("🌐 GitHub Pages enabled with GitHub Actions");
  } catch (err) {
    if (err.message.includes("already exists")) {
      console.log("✅ GitHub Pages already enabled");
    } else {
      console.error("⚠️ Error enabling GitHub Pages:", err.message);
    }
  }
}

export async function deployToGitHub(projectDir, repoName, description = "Generated by HolySmokas") {
  console.log("🚀 Starting GitHub deployment...");
  const workflowPath = path.join(projectDir, ".github/workflows/deploy.yml");
  let workflowContent = null;

  try {
    const repo = await createRepo(repoName, description);
    console.log("⏳ Waiting 3 seconds for GitHub initialization...");
    await new Promise(resolve => setTimeout(resolve, 3000));

    if (fs.existsSync(workflowPath)) {
      console.log("📋 Temporarily removing workflow file from git push...");
      workflowContent = fs.readFileSync(workflowPath, "utf8");
      fs.unlinkSync(workflowPath);
    }

    console.log("📤 Pushing project files (without workflow)...");
    const gitDir = path.join(projectDir, ".git");
    if (fs.existsSync(gitDir)) {
      fs.rmSync(gitDir, { recursive: true, force: true });
    }

    execSync("git init", { cwd: projectDir, stdio: "inherit" });
    execSync("git add .", { cwd: projectDir, stdio: "inherit" });
    execSync('git commit -m "Initial commit - project files"', { cwd: projectDir, stdio: "inherit" });
    execSync("git branch -M main", { cwd: projectDir, stdio: "inherit" });
    execSync(
      `git remote add origin https://${process.env.GIT_TOKEN}@github.com/${GIT_USERNAME}/${repoName}.git`,
      { cwd: projectDir, stdio: "inherit" }
    );
    execSync("git push -u origin main --force", { cwd: projectDir, stdio: "inherit" });
    console.log("✅ Project files pushed successfully");

    console.log("⏳ Waiting 8 seconds for GitHub to process all files...");
    await new Promise(resolve => setTimeout(resolve, 8000));

    if (workflowContent) {
      console.log("📄 Adding workflow file via GitHub API...");
      await octokit.repos.createOrUpdateFileContents({
        owner: GIT_USERNAME,
        repo: repoName,
        path: ".github/workflows/deploy.yml",
        message: "Add GitHub Actions deployment workflow",
        content: Buffer.from(workflowContent).toString("base64"),
      });
      console.log("✅ Workflow file added - GitHub Actions will now deploy");
    }

    console.log("⏳ Waiting 3 seconds before enabling Pages...");
    await new Promise(resolve => setTimeout(resolve, 3000));
    await enablePages(repoName);

    const pagesUrl = `https://${GIT_USERNAME}.github.io/${repoName}/`;
    console.log("✅ Deployment complete!");
    console.log("📍 Site will be available at:", pagesUrl);

    return {
      success: true,
      repoUrl: repo.html_url,
      pagesUrl: pagesUrl,
    };
  } catch (error) {
    console.error("❌ Deployment failed:", error.message);
    if (workflowContent && !fs.existsSync(workflowPath)) {
      const workflowDir = path.dirname(workflowPath);
      if (!fs.existsSync(workflowDir)) {
        fs.mkdirSync(workflowDir, { recursive: true });
      }
      fs.writeFileSync(workflowPath, workflowContent);
    }
    return { success: false, error: error.message };
  }
}

/**
 * Generate AI prompts based on package type
 */
function generatePromptByPackage({ name, description, category, packageType, useBoilerplate, boilerplateDescription }) {
  const baseInstructions = `
CRITICAL FORMATTING INSTRUCTIONS:
- Output EXACTLY one code block per file
- Each code block must use this EXACT format:
\`\`\`jsx:filename
code here
\`\`\`
- DO NOT add "bash", "on:", "File:", or any prefix before the filename
- DO NOT use spaces in the language tag

CRITICAL EXPORT/IMPORT RULES - FOLLOW EXACTLY:

1. COMPONENTS (pages, UI components):
   - ALWAYS use default export: export default ComponentName
   - Import: import ComponentName from './ComponentName'
   
2. CONTEXT FILES (CartContext, AuthContext, etc.):
   - Use NAMED exports: export const Provider, export const useHook
   - Import: import { Provider, useHook } from './Context'
   
3. UTILITY/HELPER FILES (if any):
   - Use named exports: export const helperFunction
   - Import: import { helperFunction } from './utils'

EXAMPLES OF CORRECT EXPORTS:

CORRECT - Component (src/pages/Shop.jsx):
function Shop() {
  return <div>Shop</div>
}
export default Shop;

CORRECT - Context (src/contexts/CartContext.jsx):
export const CartProvider = ({ children }) => {
  return <CartContext.Provider>{children}</CartContext.Provider>
}
export const useCart = () => useContext(CartContext);

CORRECT - App.jsx:
import { CartProvider } from './contexts/CartContext';
import { AuthProvider } from './contexts/AuthContext';
import Shop from './pages/Shop';

function App() {
  return (
    <CartProvider>
      <AuthProvider>
        <Shop />
      </AuthProvider>
    </CartProvider>
  )
}
export default App;

WRONG - Never do this:
export { ComponentName };  // Wrong for components
export default CartProvider;  // Wrong for contexts

REMEMBER:
- Pages/Components = default export
- Contexts = named exports
- App.jsx = default export
- All imports must match the export type

CRITICAL INDEX.HTML REQUIREMENTS:
- The index.html MUST have ONLY <script type="module" src="/src/main.jsx"></script> in the body
- DO NOT EVER include <link rel="stylesheet"> tags for CSS files
- CSS is imported via JavaScript in src/main.jsx using: import './index.css'

CRITICAL SRC/MAIN.JSX REQUIREMENTS:
- src/main.jsx MUST import the CSS file at the top: import './index.css'
- Then import React, ReactDOM, and App.jsx
- MUST import App with: import App from './App.jsx' or import App from './App'

// github.js - Update smallShop section to remove the "DO NOT GENERATE package.json" instruction
// Find this in baseInstructions (around line 198-202) and replace it:

CRITICAL PACKAGE.JSON - GENERATE THIS FILE:
- Generate a complete package.json with all necessary dependencies
- Include: react, react-dom, react-router-dom
- Include devDependencies: vite, @vitejs/plugin-react, tailwindcss, autoprefixer, postcss

Package.json MUST include:
- "name": project name
- "private": true
- "version": "1.0.0"
- "type": "module"
- "scripts": { "dev": "vite", "build": "vite build", "preview": "vite preview" }

And these dependencies:
- "react": "^18.2.0"
- "react-dom": "^18.2.0"

REMEMBER: NO <link> tags in index.html! CSS is imported in main.jsx!
REMEMBER: Components use default exports, Contexts use named exports!`;

  if (category === "landing-page" || packageType?.includes("Starter")) {
    return `Generate a complete React + Vite project for "${name}" - STARTER PACKAGE ($599).

Description: "${description}"

${baseInstructions}

CRITICAL: THIS IS A SIMPLE SINGLE-PAGE SITE - NO ROUTING!
- DO NOT include react-router-dom in dependencies
- DO NOT import any Router, Routes, Route, or Link components
- DO NOT use HashRouter or BrowserRouter anywhere
- This is a single scrolling page with sections

Example src/main.jsx (NO ROUTING):
\`\`\`jsx:src/main.jsx
import React from 'react'
import ReactDOM from 'react-dom/client'
import './index.css'
import App from './App.jsx'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
\`\`\`

CRITICAL: Use React 18 syntax with createRoot!
- Import from 'react-dom/client' NOT 'react-dom'
- Use ReactDOM.createRoot() NOT ReactDOM.render()
- This is REQUIRED for React 18

Example src/App.jsx (SIMPLE STRUCTURE):
\`\`\`jsx:src/App.jsx
import Header from './components/Header.jsx'
import Hero from './components/Hero.jsx'
import Features from './components/Features.jsx'
import Contact from './components/Contact.jsx'
import Footer from './components/Footer.jsx'

function App() {
  return (
    <div className="min-h-screen">
      <Header />
      <Hero />
      <Features />
      <Contact />
      <Footer />
    </div>
  )
}
export default App
\`\`\`

Required files for STARTER (simple landing page):
\`\`\`jsx:src/App.jsx (NO routing, just components stacked vertically)
\`\`\`html:index.html
\`\`\`jsx:src/main.jsx (NO HashRouter, just App)
\`\`\`css:src/index.css
\`\`\`javascript:tailwind.config.js
\`\`\`javascript:postcss.config.js
\`\`\`jsx:src/components/Header.jsx (use regular <a> tags with href="#section", NOT Link)
\`\`\`jsx:src/components/Hero.jsx
\`\`\`jsx:src/components/Features.jsx
\`\`\`jsx:src/components/Contact.jsx
\`\`\`jsx:src/components/Footer.jsx

Create a SIMPLE, SINGLE-PAGE website with:
- Clean hero section with headline, subheadline, and CTA button
- 3-4 feature cards highlighting key benefits
- Simple contact section with email/phone
- All sections on ONE page (no routing, no page navigation)
- Use <a href="#features"> for smooth scrolling between sections
- Modern TailwindCSS styling, fully responsive
- Professional color scheme
- Total: ONE page, 5 sections max, NO ROUTING`;
  }

  if (category === "business" || packageType?.includes("Business")) {
    return `Generate a complete React + Vite project for "${name}" - BUSINESS PACKAGE ($1,199).

Description: "${description}"

${baseInstructions}

Add react-router-dom to dependencies!

CRITICAL ROUTING SETUP - FOLLOW EXACTLY:
1. src/main.jsx MUST import HashRouter and wrap App:
   import { HashRouter } from 'react-router-dom'
   <HashRouter><App /></HashRouter>

2. src/App.jsx MUST NOT import any Router components
   Only import: Routes, Route, Link (NO HashRouter, NO BrowserRouter)
   App.jsx should return JSX wrapped in <> </> fragments, NOT <Router>

Example src/main.jsx (REQUIRED FORMAT):
\`\`\`jsx:src/main.jsx
import React from 'react'
import ReactDOM from 'react-dom/client'
import { HashRouter } from 'react-router-dom'
import './index.css'
import App from './App.jsx'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <HashRouter>
      <App />
    </HashRouter>
  </React.StrictMode>,
)
\`\`\`

CRITICAL: Use React 18 syntax!
- Import from 'react-dom/client' NOT 'react-dom'
- Use ReactDOM.createRoot() NOT ReactDOM.render()
- Wrap with HashRouter for GitHub Pages routing

CRITICAL EXPORT REQUIREMENTS:
- App.jsx MUST use: export default App (NOT export { App })
- All page components MUST use default exports
- All other components MUST use default exports
- NEVER use named exports like export { ComponentName }

Example src/App.jsx (REQUIRED FORMAT):
\`\`\`jsx:src/App.jsx
import { Routes, Route } from 'react-router-dom'
import Header from './components/Header.jsx'
import Footer from './components/Footer.jsx'
// import pages...

function App() {
  return (
    <>
      <Header />
      <Routes>
        <Route path="/" element={<Home />} />
        {/* other routes */}
      </Routes>
      <Footer />
    </>
  )
}
export default App
\`\`\`

DO NOT use BrowserRouter! DO NOT wrap Routes in a Router component in App.jsx!

Required files for BUSINESS (multi-page site):
\`\`\`jsx:src/App.jsx (with Routes ONLY, NO Router wrapper)
\`\`\`html:index.html
\`\`\`jsx:src/main.jsx (with HashRouter wrapping App)
\`\`\`css:src/index.css
\`\`\`javascript:tailwind.config.js
\`\`\`javascript:postcss.config.js
\`\`\`jsx:src/pages/Home.jsx
\`\`\`jsx:src/pages/About.jsx
\`\`\`jsx:src/pages/Services.jsx
\`\`\`jsx:src/pages/Portfolio.jsx
\`\`\`jsx:src/pages/Contact.jsx
\`\`\`jsx:src/components/Header.jsx (use Link components for navigation)
\`\`\`jsx:src/components/Hero.jsx
\`\`\`jsx:src/components/ServiceCard.jsx
\`\`\`jsx:src/components/PortfolioCard.jsx
\`\`\`jsx:src/components/Testimonials.jsx
\`\`\`jsx:src/components/ContactForm.jsx
\`\`\`jsx:src/components/Footer.jsx

Create a PROFESSIONAL MULTI-PAGE business website with:
- HashRouter in main.jsx ONLY (not in App.jsx)
- Routes defined in App.jsx using Routes and Route components
- Home: Hero, services overview, testimonials, recent work
- About: Company story, team, mission
- Services: Detailed service offerings
- Portfolio: Project gallery with 6-8 sample projects
- Contact: Full contact form with validation
- Responsive navigation menu with Link components
- Modern, corporate design with TailwindCSS`;
  }

  // github.js - Replace the entire smallShop and custom sections
  if (category === "e-commerce" || packageType?.includes("Small Shop")) {
    return `Generate a complete React + Vite e-commerce project for "${name}".

Description: "${description}"

CRITICAL: Generate ALL files from scratch. No boilerplate exists.

You MUST format code blocks as: \`\`\`language:filename

CRITICAL PACKAGE.JSON - YOU MUST GENERATE THIS:
\`\`\`json:package.json
{
  "name": "project-name",
  "private": true,
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.20.0"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^4.0.0",
    "vite": "^5.0.0",
    "tailwindcss": "^3.3.0",
    "autoprefixer": "^10.4.0",
    "postcss": "^8.4.0"
  }
}
\`\`\`

CRITICAL VITE CONFIG:
\`\`\`javascript:vite.config.js
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  base: '/{{projectName}}/'
})
\`\`\`

CRITICAL EXPORT RULES:

Regular components (Shop, Cart, Checkout, Login, AdminDashboard, Header, Footer, ProductCard, AdminProductForm, ProtectedRoute):
function ComponentName() {
  return <div>Content</div>;
}
export default ComponentName;

Context files (CartContext, AuthContext, ProductContext):
export const ProviderName = ({ children }) => { ... };
export const useHookName = () => { ... };

CRITICAL: src/index.css @import MUST be BEFORE @tailwind:
\`\`\`css:src/index.css
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');

@tailwind base;
@tailwind components;
@tailwind utilities;
\`\`\`

CRITICAL: Use React 18 syntax in main.jsx:
\`\`\`jsx:src/main.jsx
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { HashRouter } from 'react-router-dom'
import './index.css'
import App from './App.jsx'

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <HashRouter>
      <App />
    </HashRouter>
  </StrictMode>
)
\`\`\`

CRITICAL: App.jsx structure:
\`\`\`jsx:src/App.jsx
import { Routes, Route } from 'react-router-dom'
import { CartProvider } from './CartContext.jsx'
import Shop from './Shop.jsx'
import Cart from './Cart.jsx'
// ... other imports

function App() {
  return (
    <CartProvider>
      <Header />
      <Routes>
        <Route path="/" element={<Shop />} />
        <Route path="/cart" element={<Cart />} />
        {/* ... other routes */}
      </Routes>
      <Footer />
    </CartProvider>
  );
}
export default App;
\`\`\`

CRITICAL: ALL imports MUST include .jsx extension:
import Shop from './Shop.jsx' ✅
import Shop from './Shop' ❌

Generate a FULLY FUNCTIONAL E-COMMERCE SHOP:

FEATURES:
- Shop page with 8-12 sample products (use placeholder images from https://picsum.photos/400/300)
- Product cards with image, name, price, "Add to Cart" button
- Shopping cart with add/remove/quantity controls
- Cart page showing items, subtotal, quantity increase/decrease
- Checkout page with form (name, email, address, payment - UI only, no backend)
- Admin login (username: "admin", password: "admin123")
- Admin dashboard at /admin with product table
- Add/Edit/Delete products (all in React state, no backend)
- Protected admin route
- Cart icon in header showing item count
- Professional TailwindCSS design

ROUTES:
- / (Shop page)
- /cart (Cart page)
- /checkout (Checkout page)
- /login (Admin login)
- /admin (Admin dashboard - protected)

FILES TO GENERATE:
- package.json
- vite.config.js
- tailwind.config.js
- postcss.config.js
- index.html
- src/main.jsx
- src/App.jsx
- src/index.css
- src/Shop.jsx
- src/Cart.jsx
- src/Checkout.jsx
- src/Login.jsx
- src/AdminDashboard.jsx
- src/Header.jsx
- src/Footer.jsx
- src/ProductCard.jsx
- src/AdminProductForm.jsx
- src/ProtectedRoute.jsx
- src/CartContext.jsx

Make it look professional and modern!`;
  }

  // Custom/Enterprise - Full custom generation
  return `Generate a FULLY CUSTOM React + Vite project for "${name}".

Client Requirements: "${description}"

CRITICAL: Generate ALL files from scratch including package.json.

You MUST format code blocks as: \`\`\`language:filename

CRITICAL PACKAGE.JSON - YOU MUST GENERATE THIS:
\`\`\`json:package.json
{
  "name": "project-name",
  "private": true,
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^4.0.0",
    "vite": "^5.0.0",
    "tailwindcss": "^3.3.0",
    "autoprefixer": "^10.4.0",
    "postcss": "^8.4.0"
  }
}
\`\`\`

CRITICAL VITE CONFIG:
\`\`\`javascript:vite.config.js
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  base: '/{{projectName}}/'
})
\`\`\`

CRITICAL EXPORT RULES:
Components: function ComponentName() { ... } then export default ComponentName;
Context: export const Provider, export const useHook

CRITICAL: Use React 18 syntax:
import { createRoot } from 'react-dom/client'
createRoot(document.getElementById('root')).render(...)

CRITICAL: ALL imports include .jsx extension

Analyze the client requirements and create:
- Appropriate file structure
- All necessary pages and components
- Context providers if needed
- Custom features as specified
- Professional TailwindCSS design

Generate ALL required files including:
- package.json, vite.config.js, tailwind.config.js, postcss.config.js
- index.html
- src/main.jsx, src/App.jsx, src/index.css
- All components and pages needed

Be creative and build exactly what the client described!`;
}

/**
 * Generate AI-based project code using OpenAI API
 */
// github.js - Update the generateProjectCode function (around line 549-609)
export async function generateProjectCode(config) {
  console.log(`🎨 Generating AI website for: ${config.name}`);
  console.log(`📦 Package type: ${config.packageType || config.category}`);

  if (!process.env.OPENAI_API_KEY) {
    console.warn("⚠️ Missing OPENAI_API_KEY — returning default fallback code.");
    return `
      // App.jsx
      import React from 'react';
      export default function App() {
        return (
          <div style={{ textAlign: "center", padding: "2rem" }}>
            <h1>${config.name}</h1>
            <p>${config.description}</p>
            <p><em>AI generation unavailable (no API key detected)</em></p>
          </div>
        );
      }
    `;
  }

  try {
    const Anthropic = (await import("@anthropic-ai/sdk")).default;
    const anthropic = new Anthropic({ apiKey: process.env.OPENAI_API_KEY });

    const prompt = generatePromptByPackage(config);

    // github.js - Update generateProjectCode function
    const response = await anthropic.messages.create({
      model: "claude-sonnet-4-20250514",
      max_tokens: 16000,  // Increase from 8000 to 16000
      messages: [
        {
          role: "user",
          content: prompt
        }
      ],
      // backend/utils/github.js - UPDATE ONLY THIS SECTION (around line 31)

      system: `You are an expert React and Vite developer. You MUST follow these rules EXACTLY:

1. Format ALL code blocks as: \`\`\`language:filename

2. EVERY component file (Shop.jsx, Cart.jsx, Checkout.jsx, Login.jsx, etc.) MUST end with EXACTLY these two lines:
   }
   export default ComponentName;

3. NEVER use these formats:
   - export default function ComponentName() { }
   - export { ComponentName }
   - const ComponentName = () => { }; export default ComponentName;

4. Context files (CartContext.jsx) MUST use:
   - export const ProviderName
   - export const useHookName

5. ALL imports MUST include .jsx extension

6. CRITICAL: DO NOT create or import AdminDashboard.jsx or any admin features
   - App.jsx should ONLY route to: Home, Shop, Cart, Checkout
   - Do NOT add /admin route
   - Do NOT create admin panel or dashboard

7. Only generate files that are explicitly needed and referenced

EXAMPLE - This is the ONLY acceptable format for components:
\`\`\`jsx:src/components/Navbar.jsx
import { Link } from 'react-router-dom';

function Navbar() {
  return <nav>Navigation</nav>;
}

export default Navbar;
\`\`\`

CRITICAL: Every single component file MUST have "export default ComponentName" as the last line.
Do NOT create any admin features, dashboards, or management panels.
Do NOT deviate from these export patterns under any circumstances.`,
      temperature: 0.3,
    });

    const generatedCode = response.content[0]?.text?.trim();
    if (!generatedCode) throw new Error("Empty AI response");

    console.log("✅ AI code generated successfully");
    return generatedCode;
  } catch (err) {
    console.error("❌ Error generating project code:", err.message);
    return `
      // App.jsx
      import React from 'react';
      export default function App() {
        return (
          <div style={{ textAlign: "center", padding: "2rem" }}>
            <h1>${config.name}</h1>
            <p>${config.description}</p>
            <p><em>AI generation failed: ${err.message}</em></p>
          </div>
        );
      }
    `;
  }
}