//- backend/utils/github.js
import { Octokit } from "@octokit/rest";
import fs from "fs";
import path from "path";
import { execSync } from "child_process";
import dotenv from "dotenv";

dotenv.config();

/** Sanitize description for GitHub */
function sanitizeDescription(description) {
  if (!description) return "Generated site";

  return description
    .replace(/[\r\n\t]/g, ' ')  // Replace control characters
    .replace(/[^\x20-\x7E]/g, '') // Remove non-printable characters
    .replace(/\s+/g, ' ')  // Collapse spaces
    .trim()
    .substring(0, 350);
}

const octokit = new Octokit({ auth: process.env.GIT_TOKEN });
const GIT_USERNAME = process.env.GIT_USERNAME;


export async function createRepo(repoName, description = "Generated site") {
  try {
    const sanitizedDescription = sanitizeDescription(description);

    const response = await octokit.repos.createForAuthenticatedUser({
      name: repoName,
      description: sanitizedDescription,
      private: false,
      auto_init: true,
    });
    console.log("✅ Repository created:", response.data.html_url);
    return response.data;
  } catch (error) {
    console.error("❌ Failed to create repository:", error.message);
    throw error;
  }
}

export async function enablePages(repoName) {
  try {
    await octokit.repos.createPagesSite({
      owner: GIT_USERNAME,
      repo: repoName,
      build_type: "workflow",
    });
    console.log("🌐 GitHub Pages enabled with GitHub Actions");
  } catch (err) {
    if (err.message.includes("already exists")) {
      console.log("✅ GitHub Pages already enabled");
    } else {
      console.error("⚠️ Error enabling GitHub Pages:", err.message);
    }
  }
}

export async function deployToGitHub(projectDir, repoName, description = "Generated by HolySmokas") {
  console.log("🚀 Starting GitHub deployment...");
  const workflowPath = path.join(projectDir, ".github/workflows/deploy.yml");
  let workflowContent = null;

  try {
    const repo = await createRepo(repoName, description);
    console.log("⏳ Waiting 3 seconds for GitHub initialization...");
    await new Promise(resolve => setTimeout(resolve, 3000));

    if (fs.existsSync(workflowPath)) {
      console.log("📋 Temporarily removing workflow file from git push...");
      workflowContent = fs.readFileSync(workflowPath, "utf8");
      fs.unlinkSync(workflowPath);
    }

    console.log("📤 Pushing project files (without workflow)...");
    const gitDir = path.join(projectDir, ".git");
    if (fs.existsSync(gitDir)) {
      fs.rmSync(gitDir, { recursive: true, force: true });
    }

    execSync("git init", { cwd: projectDir, stdio: "inherit" });
    execSync("git add .", { cwd: projectDir, stdio: "inherit" });
    execSync('git commit -m "Initial commit - project files"', { cwd: projectDir, stdio: "inherit" });
    execSync("git branch -M main", { cwd: projectDir, stdio: "inherit" });
    execSync(
      `git remote add origin https://${process.env.GIT_TOKEN}@github.com/${GIT_USERNAME}/${repoName}.git`,
      { cwd: projectDir, stdio: "inherit" }
    );
    execSync("git push -u origin main --force", { cwd: projectDir, stdio: "inherit" });
    console.log("✅ Project files pushed successfully");

    console.log("⏳ Waiting 8 seconds for GitHub to process all files...");
    await new Promise(resolve => setTimeout(resolve, 8000));

    if (workflowContent) {
      console.log("📄 Adding workflow file via GitHub API...");
      await octokit.repos.createOrUpdateFileContents({
        owner: GIT_USERNAME,
        repo: repoName,
        path: ".github/workflows/deploy.yml",
        message: "Add GitHub Actions deployment workflow",
        content: Buffer.from(workflowContent).toString("base64"),
      });
      console.log("✅ Workflow file added - GitHub Actions will now deploy");
    }

    console.log("⏳ Waiting 3 seconds before enabling Pages...");
    await new Promise(resolve => setTimeout(resolve, 3000));
    await enablePages(repoName);

    const pagesUrl = `https://${GIT_USERNAME}.github.io/${repoName}/`;
    console.log("✅ Deployment complete!");
    console.log("📍 Site will be available at:", pagesUrl);

    return {
      success: true,
      repoUrl: repo.html_url,
      pagesUrl: pagesUrl,
    };
  } catch (error) {
    console.error("❌ Deployment failed:", error.message);
    if (workflowContent && !fs.existsSync(workflowPath)) {
      const workflowDir = path.dirname(workflowPath);
      if (!fs.existsSync(workflowDir)) {
        fs.mkdirSync(workflowDir, { recursive: true });
      }
      fs.writeFileSync(workflowPath, workflowContent);
    }
    return { success: false, error: error.message };
  }
}

/**
 * Generate AI prompts based on package type
 */
/**
 * Parse user requirements to determine which pages/components to generate
 * Based on the "Must-Have Features" field from contact form
 */
function parseUserRequirements(formData) {
  const mustHaveFeatures = (formData.mustHaveFeatures || formData.description || '').toLowerCase();
  const pages = new Set(['home']); // Home is always required
  const components = new Set(['header', 'footer']); // Always needed

  console.log(`📋 Parsing user requirements: "${mustHaveFeatures}"`);

  // Parse for page keywords
  const pageKeywords = {
    'about': ['about', 'about us', 'who we are', 'our story', 'team', 'mission'],
    'services': ['services', 'what we do', 'offerings', 'what we offer', 'service'],
    'portfolio': ['portfolio', 'work', 'projects', 'gallery', 'showcase', 'examples', 'our work'],
    'contact': ['contact', 'get in touch', 'reach us', 'contact form', 'contact us'],
    'shop': ['shop', 'store', 'products', 'buy', 'purchase', 'e-commerce', 'ecommerce', 'cart'],
    'blog': ['blog', 'articles', 'news', 'posts'],
    'pricing': ['pricing', 'plans', 'packages', 'price']
  };

  const logoInstructions = `
🖼️ LOGO INTEGRATION:
- Logo file will be available at: /logo.png, /logo.jpg, or /logo.svg
- Use logo in Header component: <img src="/logo.png" alt="Business Logo" />
- Fallback if no logo: Use business name as text
- Recommended logo placement: Top-left of navigation bar
- Max logo height: 60px for header, responsive on mobile

Example Header with Logo:
\`\`\`jsx:src/components/Header.jsx
function Header() {
  return (
    <header className="bg-white shadow-md">
      <nav className="container mx-auto px-4 py-4 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <img src="/logo.png" alt="Logo" className="h-12" onError={(e) => e.target.style.display='none'} />
          <span className="text-2xl font-bold">Business Name</span>
        </div>
        {/* Nav links */}
      </nav>
    </header>
  );
}
export default Header;
\`\`\`
`;

  // Add this to your baseInstructions
  const baseInstructions = `
${existingInstructions}
${logoInstructions}
${legalPagesInstructions}
`;
  // Check which pages are mentioned
  for (const [page, keywords] of Object.entries(pageKeywords)) {
    if (keywords.some(keyword => mustHaveFeatures.includes(keyword))) {
      pages.add(page);
      console.log(`  ✅ Found: ${page} page`);
    }
  }

  // Determine components based on pages
  if (pages.has('services')) {
    components.add('servicecard');
  }
  if (pages.has('portfolio') || mustHaveFeatures.includes('gallery')) {
    components.add('portfoliocard');
  }
  if (pages.has('contact')) {
    components.add('contactform');
  }
  if (mustHaveFeatures.includes('testimonial') || mustHaveFeatures.includes('review')) {
    components.add('testimonials');
    pages.add('testimonials');
  }

  // Always add hero for visual appeal
  components.add('hero');

  console.log(`🎯 Pages to generate: ${Array.from(pages).join(', ')}`);
  console.log(`🎯 Components to generate: ${Array.from(components).join(', ')}`);

  return {
    pages: Array.from(pages),
    components: Array.from(components)
  };
}

/**
 * Get description for each page type based on user requirements
 */
function getPageDescription(pageName, config) {
  const descriptions = {
    'home': `Hero section showcasing ${config.name}, overview of services/offerings, call-to-action buttons`,
    'about': `Company story for ${config.name}, mission statement, team information, values`,
    'services': `Detailed service offerings for ${config.name}, what you provide, benefits`,
    'portfolio': `Project showcase/gallery with 6-8 example projects for ${config.name}`,
    'contact': `Contact form with name, email, message fields. Include business contact info`,
    'shop': `Product listings with images, prices, add-to-cart functionality`,
    'blog': `Article listings with previews and read-more links`,
    'pricing': `Pricing plans and packages with feature comparisons`,
    'testimonials': `Customer testimonials and reviews for ${config.name}`
  };

  return descriptions[pageName] || `${pageName} content based on: ${config.description}`;
}

function generatePromptByPackage({ name, description, category, packageType, useBoilerplate, boilerplateDescription, mustHaveFeatures }) {
  const currentYear = new Date().getFullYear();
  const currentDate = new Date().toLocaleDateString();

  const baseInstructions = `
CRITICAL FORMATTING INSTRUCTIONS:
- Output EXACTLY one code block per file
- Each code block must use this EXACT format:
\`\`\`jsx:filename
code here
\`\`\`
- DO NOT add "bash", "on:", "File:", or any prefix before the filename
- DO NOT use spaces in the language tag

⚠️⚠️⚠️ CRITICAL CSS RULES - USE ONLY VALID TAILWIND CLASSES ⚠️⚠️⚠️

FORBIDDEN CSS CLASSES (DO NOT USE - THEY BREAK THE BUILD):
❌ resize-vertical (INVALID - causes build failure)
❌ resize-horizontal (INVALID - causes build failure)
❌ resize-none (INVALID - causes build failure)
❌ resize-both (INVALID - causes build failure)
❌ resize (INVALID - causes build failure)

✅ ONLY USE STANDARD TAILWIND UTILITY CLASSES:
- Layout: flex, grid, block, inline, hidden
- Sizing: w-full, h-screen, max-w-7xl, min-h-screen
- Spacing: p-4, m-8, space-y-4, gap-6
- Typography: text-lg, font-bold, text-center, leading-relaxed
- Colors: bg-blue-500, text-white, border-gray-300
- Effects: shadow-lg, rounded-lg, hover:bg-blue-600, transition

⚠️⚠️⚠️ CRITICAL EXPORT/IMPORT RULES - FOLLOW EXACTLY OR BUILD WILL FAIL ⚠️⚠️⚠️

1. COMPONENTS (pages, UI components):
   - ALWAYS use default export: export default ComponentName
   - Import: import ComponentName from './ComponentName'
   
2. CONTEXT FILES (CartContext, AuthContext, etc.):
   - Use NAMED exports: export const Provider, export const useHook
   - Import: import { Provider, useHook } from './Context'
   
3. UTILITY/HELPER FILES (if any):
   - Use named exports: export const helperFunction
   - Import: import { helperFunction } from './utils'

⚠️ MANDATORY: EVERY .jsx COMPONENT FILE MUST END WITH "export default ComponentName" ⚠️

EXAMPLES OF CORRECT EXPORTS:

✅ CORRECT - Component (src/pages/Shop.jsx):
function Shop() {
  return <div>Shop</div>
}
export default Shop;

✅ CORRECT - Component (src/pages/Portfolio.jsx):
function Portfolio() {
  return <div>Portfolio</div>
}
export default Portfolio;

✅ CORRECT - Component (src/pages/Home.jsx):
function Home() {
  return <div>Home</div>
}
export default Home;

✅ CORRECT - Context (src/contexts/CartContext.jsx):
export const CartProvider = ({ children }) => {
  return <CartContext.Provider>{children}</CartContext.Provider>
}
export const useCart = () => useContext(CartContext);

✅ CORRECT - App.jsx:
import { CartProvider } from './contexts/CartContext';
import { AuthProvider } from './contexts/AuthContext';
import Shop from './pages/Shop';

function App() {
  return (
    <CartProvider>
      <AuthProvider>
        <Shop />
      </AuthProvider>
    </CartProvider>
  )
}
export default App;

❌ WRONG - Never do this:
export { ComponentName };  // ❌ Wrong for components - BUILD WILL FAIL
export default CartProvider;  // ❌ Wrong for contexts
const Home = () => <div>Home</div>; // ❌ Missing export default

⚠️⚠️⚠️ MANDATORY CHECKLIST - VERIFY EVERY FILE: ⚠️⚠️⚠️
- ✅ src/App.jsx → ends with "export default App"
- ✅ src/pages/Home.jsx → ends with "export default Home"
- ✅ src/pages/About.jsx → ends with "export default About"
- ✅ src/pages/Services.jsx → ends with "export default Services"
- ✅ src/pages/Portfolio.jsx → ends with "export default Portfolio"
- ✅ src/pages/Contact.jsx → ends with "export default Contact"
- ✅ Every component file → ends with "export default ComponentName"

REMEMBER:
- Pages/Components = default export (MANDATORY)
- Contexts = named exports
- App.jsx = default export (MANDATORY)
- All imports must match the export type
- NO EXCEPTIONS - BUILD WILL FAIL WITHOUT PROPER EXPORTS

CRITICAL INDEX.HTML REQUIREMENTS:
- The index.html MUST have ONLY <script type="module" src="/src/main.jsx"></script> in the body
- DO NOT EVER include <link rel="stylesheet"> tags for CSS files
- CSS is imported via JavaScript in src/main.jsx using: import './index.css'

CRITICAL SRC/MAIN.JSX REQUIREMENTS:
- src/main.jsx MUST import the CSS file at the top: import './index.css'
- Then import React, ReactDOM, and App.jsx
- MUST import App with: import App from './App.jsx' or import App from './App'

// github.js - Update smallShop section to remove the "DO NOT GENERATE package.json" instruction
// Find this in baseInstructions (around line 198-202) and replace it:

CRITICAL PACKAGE.JSON - GENERATE THIS FILE:
- Generate a complete package.json with all necessary dependencies
- Include: react, react-dom, react-router-dom
- Include devDependencies: vite, @vitejs/plugin-react, tailwindcss, autoprefixer, postcss

Package.json MUST include:
- "name": project name
- "private": true
- "version": "1.0.0"
- "type": "module"
- "scripts": { "dev": "vite", "build": "vite build", "preview": "vite preview" }

And these dependencies:
- "react": "^18.2.0"
- "react-dom": "^18.2.0"

REMEMBER: NO <link> tags in index.html! CSS is imported in main.jsx!
REMEMBER: Components use default exports, Contexts use named exports!`;

  // ==================== ADD LEGAL PAGES INSTRUCTIONS HERE ====================
  const legalPagesInstructions = `

⚖️⚖️⚖️ MANDATORY LEGAL PAGES - MUST GENERATE FOR EVERY PROJECT ⚖️⚖️⚖️

CRITICAL: Generate these 4 legal pages in the /public folder:
1. public/terms-of-service.html
2. public/privacy-policy.html
3. public/cookies.html
4. public/disclaimer.html

Each page MUST:
- Be a complete, standalone HTML page with full <html>, <head>, and <body>
- Include responsive TailwindCSS styling via CDN
- Have navigation back to main site
- Use professional, industry-standard language
- Be broad and general (not specific to any particular business)
- Include current year: ${currentYear}
- Include business name: {{businessName}}

EXAMPLE STRUCTURE for public/terms-of-service.html:
\`\`\`html:public/terms-of-service.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terms of Service - {{businessName}}</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-50">
    <div class="max-w-4xl mx-auto px-4 py-12">
        <div class="bg-white rounded-lg shadow-lg p-8">
            <div class="mb-8">
                <a href="/" class="text-blue-600 hover:text-blue-800 flex items-center gap-2">
                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"/>
                    </svg>
                    Back to Home
                </a>
            </div>
            
            <h1 class="text-4xl font-bold mb-4">Terms of Service</h1>
            <p class="text-gray-600 mb-8">Last Updated: ${currentDate}</p>
            
            <div class="prose max-w-none">
                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">1. Acceptance of Terms</h2>
                    <p class="text-gray-700 mb-4">
                        By accessing and using {{businessName}}'s website and services, you accept and agree to be bound by the terms and provision of this agreement.
                    </p>
                </section>

                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">2. Use License</h2>
                    <p class="text-gray-700 mb-4">
                        Permission is granted to temporarily access the materials (information or software) on {{businessName}}'s website for personal, non-commercial transitory viewing only.
                    </p>
                    <ul class="list-disc pl-6 text-gray-700 mb-4">
                        <li>modify or copy the materials;</li>
                        <li>use the materials for any commercial purpose;</li>
                        <li>attempt to decompile or reverse engineer any software;</li>
                        <li>remove any copyright or proprietary notations;</li>
                        <li>transfer the materials to another person or "mirror" the materials on any other server.</li>
                    </ul>
                </section>

                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">3. Disclaimer</h2>
                    <p class="text-gray-700 mb-4">
                        The materials on {{businessName}}'s website are provided on an 'as is' basis. {{businessName}} makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.
                    </p>
                </section>

                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">4. Limitations</h2>
                    <p class="text-gray-700 mb-4">
                        In no event shall {{businessName}} or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on {{businessName}}'s website.
                    </p>
                </section>

                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">5. Accuracy of Materials</h2>
                    <p class="text-gray-700 mb-4">
                        The materials appearing on {{businessName}}'s website could include technical, typographical, or photographic errors. {{businessName}} does not warrant that any of the materials on its website are accurate, complete or current.
                    </p>
                </section>

                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">6. Links</h2>
                    <p class="text-gray-700 mb-4">
                        {{businessName}} has not reviewed all of the sites linked to its website and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by {{businessName}} of the site.
                    </p>
                </section>

                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">7. Modifications</h2>
                    <p class="text-gray-700 mb-4">
                        {{businessName}} may revise these terms of service for its website at any time without notice. By using this website you are agreeing to be bound by the then current version of these terms of service.
                    </p>
                </section>

                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">8. Governing Law</h2>
                    <p class="text-gray-700 mb-4">
                        These terms and conditions are governed by and construed in accordance with the laws and you irrevocably submit to the exclusive jurisdiction of the courts in that location.
                    </p>
                </section>
            </div>
        </div>
    </div>
</body>
</html>
\`\`\`

EXAMPLE STRUCTURE for public/privacy-policy.html:
\`\`\`html:public/privacy-policy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Privacy Policy - {{businessName}}</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-50">
    <div class="max-w-4xl mx-auto px-4 py-12">
        <div class="bg-white rounded-lg shadow-lg p-8">
            <div class="mb-8">
                <a href="/" class="text-blue-600 hover:text-blue-800 flex items-center gap-2">
                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"/>
                    </svg>
                    Back to Home
                </a>
            </div>
            
            <h1 class="text-4xl font-bold mb-4">Privacy Policy</h1>
            <p class="text-gray-600 mb-8">Last Updated: ${currentDate}</p>
            
            <div class="prose max-w-none">
                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">1. Information We Collect</h2>
                    <p class="text-gray-700 mb-4">
                        We collect information that you provide directly to us, including when you create an account, make a purchase, subscribe to our newsletter, or contact us for support.
                    </p>
                    <ul class="list-disc pl-6 text-gray-700 mb-4">
                        <li>Name and contact information</li>
                        <li>Email address</li>
                        <li>Phone number</li>
                        <li>Billing and shipping address</li>
                        <li>Payment information</li>
                    </ul>
                </section>

                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">2. How We Use Your Information</h2>
                    <p class="text-gray-700 mb-4">
                        We use the information we collect to:
                    </p>
                    <ul class="list-disc pl-6 text-gray-700 mb-4">
                        <li>Provide, maintain, and improve our services</li>
                        <li>Process transactions and send related information</li>
                        <li>Send you technical notices and support messages</li>
                        <li>Respond to your comments and questions</li>
                        <li>Send you marketing communications (with your consent)</li>
                    </ul>
                </section>

                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">3. Information Sharing</h2>
                    <p class="text-gray-700 mb-4">
                        We do not sell, trade, or rent your personal information to third parties. We may share your information with:
                    </p>
                    <ul class="list-disc pl-6 text-gray-700 mb-4">
                        <li>Service providers who assist in our operations</li>
                        <li>Professional advisers including lawyers and accountants</li>
                        <li>Law enforcement when required by law</li>
                    </ul>
                </section>

                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">4. Data Security</h2>
                    <p class="text-gray-700 mb-4">
                        We implement appropriate technical and organizational measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction.
                    </p>
                </section>

                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">5. Cookies</h2>
                    <p class="text-gray-700 mb-4">
                        We use cookies and similar tracking technologies to track activity on our website. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. See our <a href="cookies.html" class="text-blue-600 hover:underline">Cookie Policy</a> for more details.
                    </p>
                </section>

                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">6. Your Rights</h2>
                    <p class="text-gray-700 mb-4">
                        You have the right to:
                    </p>
                    <ul class="list-disc pl-6 text-gray-700 mb-4">
                        <li>Access your personal information</li>
                        <li>Correct inaccurate data</li>
                        <li>Request deletion of your data</li>
                        <li>Object to processing of your data</li>
                        <li>Request data portability</li>
                    </ul>
                </section>

                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">7. Children's Privacy</h2>
                    <p class="text-gray-700 mb-4">
                        Our services are not directed to children under 13. We do not knowingly collect personal information from children under 13. If you become aware that a child has provided us with personal information, please contact us.
                    </p>
                </section>

                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">8. Contact Us</h2>
                    <p class="text-gray-700 mb-4">
                        If you have questions about this Privacy Policy, please contact us at the information provided on our website.
                    </p>
                </section>
            </div>
        </div>
    </div>
</body>
</html>
\`\`\`

EXAMPLE STRUCTURE for public/cookies.html:
\`\`\`html:public/cookies.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cookie Policy - {{businessName}}</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-50">
    <div class="max-w-4xl mx-auto px-4 py-12">
        <div class="bg-white rounded-lg shadow-lg p-8">
            <div class="mb-8">
                <a href="/" class="text-blue-600 hover:text-blue-800 flex items-center gap-2">
                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"/>
                    </svg>
                    Back to Home
                </a>
            </div>
            
            <h1 class="text-4xl font-bold mb-4">Cookie Policy</h1>
            <p class="text-gray-600 mb-8">Last Updated: ${currentDate}</p>
            
            <div class="prose max-w-none">
                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">What Are Cookies</h2>
                    <p class="text-gray-700 mb-4">
                        Cookies are small text files that are placed on your device when you visit our website. They help us provide you with a better experience and allow certain features to work.
                    </p>
                </section>

                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">How We Use Cookies</h2>
                    <p class="text-gray-700 mb-4">
                        We use cookies for various purposes:
                    </p>
                    <ul class="list-disc pl-6 text-gray-700 mb-4">
                        <li><strong>Essential Cookies:</strong> Required for the website to function properly</li>
                        <li><strong>Analytics Cookies:</strong> Help us understand how visitors use our site</li>
                        <li><strong>Functional Cookies:</strong> Remember your preferences and choices</li>
                        <li><strong>Marketing Cookies:</strong> Used to show relevant advertisements</li>
                    </ul>
                </section>

                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">Types of Cookies We Use</h2>
                    
                    <div class="mb-6">
                        <h3 class="text-xl font-semibold mb-2">Session Cookies</h3>
                        <p class="text-gray-700">Temporary cookies that expire when you close your browser.</p>
                    </div>
                    
                    <div class="mb-6">
                        <h3 class="text-xl font-semibold mb-2">Persistent Cookies</h3>
                        <p class="text-gray-700">Remain on your device for a set period or until you delete them.</p>
                    </div>
                    
                    <div class="mb-6">
                        <h3 class="text-xl font-semibold mb-2">First-Party Cookies</h3>
                        <p class="text-gray-700">Set by {{businessName}} directly.</p>
                    </div>
                    
                    <div class="mb-6">
                        <h3 class="text-xl font-semibold mb-2">Third-Party Cookies</h3>
                        <p class="text-gray-700">Set by external services we use (e.g., Google Analytics).</p>
                    </div>
                </section>

                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">Managing Cookies</h2>
                    <p class="text-gray-700 mb-4">
                        You can control and manage cookies in various ways:
                    </p>
                    <ul class="list-disc pl-6 text-gray-700 mb-4">
                        <li>Browser settings: Most browsers allow you to refuse cookies</li>
                        <li>Delete existing cookies from your device</li>
                        <li>Block third-party cookies specifically</li>
                        <li>Receive warnings before cookies are stored</li>
                    </ul>
                    <p class="text-gray-700 mb-4">
                        Please note that disabling cookies may affect your experience on our website.
                    </p>
                </section>

                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">Third-Party Services</h2>
                    <p class="text-gray-700 mb-4">
                        We may use third-party services that use cookies, including:
                    </p>
                    <ul class="list-disc pl-6 text-gray-700 mb-4">
                        <li>Google Analytics for website analytics</li>
                        <li>Social media platforms for sharing content</li>
                        <li>Advertising networks for targeted ads</li>
                    </ul>
                </section>

                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">Updates to This Policy</h2>
                    <p class="text-gray-700 mb-4">
                        We may update this Cookie Policy from time to time. Any changes will be posted on this page with an updated revision date.
                    </p>
                </section>

                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">Contact Us</h2>
                    <p class="text-gray-700 mb-4">
                        If you have questions about our use of cookies, please contact us through the information provided on our website.
                    </p>
                </section>
            </div>
        </div>
    </div>
</body>
</html>
\`\`\`

EXAMPLE STRUCTURE for public/disclaimer.html:
\`\`\`html:public/disclaimer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Disclaimer - {{businessName}}</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-50">
    <div class="max-w-4xl mx-auto px-4 py-12">
        <div class="bg-white rounded-lg shadow-lg p-8">
            <div class="mb-8">
                <a href="/" class="text-blue-600 hover:text-blue-800 flex items-center gap-2">
                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"/>
                    </svg>
                    Back to Home
                </a>
            </div>
            
            <h1 class="text-4xl font-bold mb-4">Disclaimer</h1>
            <p class="text-gray-600 mb-8">Last Updated: ${currentDate}</p>
            
            <div class="prose max-w-none">
                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">Website Disclaimer</h2>
                    <p class="text-gray-700 mb-4">
                        The information provided by {{businessName}} on this website is for general informational purposes only. All information on the site is provided in good faith, however we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability or completeness of any information on the site.
                    </p>
                </section>

                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">External Links Disclaimer</h2>
                    <p class="text-gray-700 mb-4">
                        The site may contain (or you may be sent through the site) links to other websites or content belonging to or originating from third parties. Such external links are not investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability or completeness by us.
                    </p>
                </section>

                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">Professional Disclaimer</h2>
                    <p class="text-gray-700 mb-4">
                        The site cannot and does not contain professional advice. The information is provided for general informational and educational purposes only and is not a substitute for professional advice. Accordingly, before taking any actions based upon such information, we encourage you to consult with the appropriate professionals.
                    </p>
                </section>

                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">Affiliates Disclaimer</h2>
                    <p class="text-gray-700 mb-4">
                        The site may contain links to affiliate websites, and we may receive an affiliate commission for any purchases made by you on the affiliate website using such links.
                    </p>
                </section>

                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">Testimonials Disclaimer</h2>
                    <p class="text-gray-700 mb-4">
                        The site may contain testimonials by users of our products and/or services. These testimonials reflect the real-life experiences and opinions of such users. However, the experiences are personal to those particular users, and may not necessarily be representative of all users of our products and/or services.
                    </p>
                </section>

                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">Errors and Omissions Disclaimer</h2>
                    <p class="text-gray-700 mb-4">
                        While we have made every attempt to ensure that the information contained in this site has been obtained from reliable sources, {{businessName}} is not responsible for any errors or omissions or for the results obtained from the use of this information.
                    </p>
                </section>

                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">Fair Use Disclaimer</h2>
                    <p class="text-gray-700 mb-4">
                        This site may use copyrighted material which has not always been specifically authorized by the copyright owner. We believe this constitutes a 'fair use' of any such copyrighted material as provided for in section 107 of the US Copyright Law.
                    </p>
                </section>

                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">Views Expressed Disclaimer</h2>
                    <p class="text-gray-700 mb-4">
                        The site may contain views and opinions which are those of the authors and do not necessarily reflect the official policy or position of any other author, agency, organization, employer or company, including {{businessName}}.
                    </p>
                </section>

                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">No Responsibility Disclaimer</h2>
                    <p class="text-gray-700 mb-4">
                        The information on the site is provided with the understanding that {{businessName}} is not herein engaged in rendering legal, accounting, tax, or other professional advice and services. As such, it should not be used as a substitute for consultation with professional accounting, tax, legal or other competent advisers.
                    </p>
                </section>

                <section class="mb-8">
                    <h2 class="text-2xl font-semibold mb-4">Contact Us</h2>
                    <p class="text-gray-700 mb-4">
                        If you have any questions about this Disclaimer, please contact us through the information provided on our website.
                    </p>
                </section>
            </div>
        </div>
    </div>
</body>
</html>
\`\`\`

CRITICAL FOOTER UPDATE:
Every Footer component MUST include links to these legal pages:

\`\`\`jsx
<footer className="bg-gray-900 text-white py-12">
  <div className="container mx-auto px-4">
    {/* ... other footer content ... */}
    
    <div className="border-t border-gray-800 mt-8 pt-8 text-center">
      <div className="flex flex-wrap justify-center gap-6 mb-4">
        <a href="terms-of-service.html" className="text-gray-400 hover:text-white transition">
          Terms of Service
        </a>
        <a href="privacy-policy.html" className="text-gray-400 hover:text-white transition">
          Privacy Policy
        </a>
        <a href="cookies.html" className="text-gray-400 hover:text-white transition">
          Cookie Policy
        </a>
        <a href="disclaimer.html" className="text-gray-400 hover:text-white transition">
          Disclaimer
        </a>
      </div>
      <p className="text-gray-400">
        &copy; ${currentYear} {{businessName}}. All rights reserved.
      </p>
    </div>
  </div>
</footer>
\`\`\`

✅ MANDATORY CHECKLIST:
- [ ] Generate all 4 legal pages in /public folder
- [ ] Use TailwindCSS CDN (not imports)
- [ ] Include back-to-home navigation
- [ ] Replace {{businessName}} with actual business name
- [ ] Update Footer component with legal page links
- [ ] Use current year: ${currentYear}
`;

  // Combine base instructions with legal pages instructions
  const fullInstructions = baseInstructions + legalPagesInstructions;

  // Continue with the rest of your existing logic...
  if (category === "landing-page" || packageType?.includes("Starter")) {
    return `Generate a complete React + Vite project for "${name}" - STARTER PACKAGE ($599).

Description: "${description}"

${fullInstructions}

CRITICAL: THIS IS A SIMPLE SINGLE-PAGE SITE - NO ROUTING!
- DO NOT include react-router-dom in dependencies
- DO NOT import any Router, Routes, Route, or Link components
- DO NOT use HashRouter or BrowserRouter anywhere
- This is a single scrolling page with sections

Example src/main.jsx (NO ROUTING):
\`\`\`jsx:src/main.jsx
import React from 'react'
import ReactDOM from 'react-dom/client'
import './index.css'
import App from './App.jsx'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
\`\`\`

CRITICAL: Use React 18 syntax with createRoot!
- Import from 'react-dom/client' NOT 'react-dom'
- Use ReactDOM.createRoot() NOT ReactDOM.render()
- This is REQUIRED for React 18

Example src/App.jsx (SIMPLE STRUCTURE):
\`\`\`jsx:src/App.jsx
import Header from './components/Header.jsx'
import Hero from './components/Hero.jsx'
import Features from './components/Features.jsx'
import Contact from './components/Contact.jsx'
import Footer from './components/Footer.jsx'

function App() {
  return (
    <div className="min-h-screen">
      <Header />
      <Hero />
      <Features />
      <Contact />
      <Footer />
    </div>
  )
}
export default App
\`\`\`

Required files for STARTER (simple landing page):
\`\`\`jsx:src/App.jsx (NO routing, just components stacked vertically)
\`\`\`html:index.html
\`\`\`jsx:src/main.jsx (NO HashRouter, just App)
\`\`\`css:src/index.css
\`\`\`javascript:tailwind.config.js
\`\`\`javascript:postcss.config.js
\`\`\`jsx:src/components/Header.jsx (use regular <a> tags with href="#section", NOT Link)
\`\`\`jsx:src/components/Hero.jsx
\`\`\`jsx:src/components/Features.jsx
\`\`\`jsx:src/components/Contact.jsx
\`\`\`jsx:src/components/Footer.jsx

Create a SIMPLE, SINGLE-PAGE website with:
- Clean hero section with headline, subheadline, and CTA button
- 3-4 feature cards highlighting key benefits
- Simple contact section with email/phone
- All sections on ONE page (no routing, no page navigation)
- Use <a href="#features"> for smooth scrolling between sections
- Modern TailwindCSS styling, fully responsive
- Professional color scheme
- Total: ONE page, 5 sections max, NO ROUTING`;
  }

  if (category === "business" || packageType?.includes("Business")) {
    // Parse user requirements from form
    const requirements = parseUserRequirements({ name, description, mustHaveFeatures });

    // Build file list dynamically based on what user wants
    const pageFiles = requirements.pages.map(p =>
      `src/pages/${p.charAt(0).toUpperCase() + p.slice(1)}.jsx`
    );

    const componentFiles = requirements.components.map(c =>
      `src/components/${c.charAt(0).toUpperCase() + c.slice(1)}.jsx`
    );

    const allFiles = [
      'package.json',
      'index.html',
      'src/main.jsx',
      'src/index.css',
      'tailwind.config.js',
      'postcss.config.js',
      'src/App.jsx',
      ...pageFiles,
      ...componentFiles
    ];

    const totalFiles = allFiles.length;
    console.log(`📊 Will generate ${totalFiles} files for business website`);

    return `Generate a complete React + Vite project for "${name}" - BUSINESS PACKAGE ($1,199).

Description: "${description}"

USER'S MUST-HAVE FEATURES (TOP PRIORITY):
"${mustHaveFeatures || description}"

${fullInstructions}

Add react-router-dom to dependencies!

CRITICAL ROUTING SETUP - FOLLOW EXACTLY:
1. src/main.jsx MUST import HashRouter and wrap App:
   import { HashRouter } from 'react-router-dom'
   <HashRouter><App /></HashRouter>

2. src/App.jsx MUST NOT import any Router components
   Only import: Routes, Route (NO HashRouter, NO BrowserRouter)

Example src/main.jsx (REQUIRED FORMAT):
\`\`\`jsx:src/main.jsx
import React from 'react'
import ReactDOM from 'react-dom/client'
import { HashRouter } from 'react-router-dom'
import './index.css'
import App from './App.jsx'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <HashRouter>
      <App />
    </HashRouter>
  </React.StrictMode>,
)
\`\`\`

Example src/App.jsx (REQUIRED FORMAT):
\`\`\`jsx:src/App.jsx
import { Routes, Route } from 'react-router-dom'
import Header from './components/Header.jsx'
import Footer from './components/Footer.jsx'
import Home from './pages/Home.jsx'
// ... import other pages

function App() {
  return (
    <>
      <Header />
      <Routes>
        <Route path="/" element={<Home />} />
        {/* other routes */}
      </Routes>
      <Footer />
    </>
  )
}
export default App
\`\`\`

⚠️⚠️⚠️ CRITICAL: YOU MUST GENERATE EXACTLY THESE ${totalFiles} FILES ⚠️⚠️⚠️

Required files (generate ALL, NO MORE, NO LESS):
${allFiles.map(f => `\`\`\`jsx:${f}`).join('\n')}

DO NOT generate files not listed above.
DO NOT skip any files listed above.

PAGES TO CREATE (based on user requirements):
${requirements.pages.map(p => `- ${p.toUpperCase()} PAGE: ${getPageDescription(p, { name, description, mustHaveFeatures })}`).join('\n')}

COMPONENTS TO CREATE:
${requirements.components.map(c => `- ${c.toUpperCase()}: Reusable component`).join('\n')}

Design Guidelines:
- Modern, professional, corporate aesthetic
- Responsive with TailwindCSS
- Mobile-first approach
- All content relates to "${name}"
- HashRouter in main.jsx ONLY
- Routes in App.jsx WITHOUT Router wrapper
- Every component ends with "export default ComponentName"`;
  }

  // Continue with the rest of your existing package types...
  // (e-commerce, custom, etc.) - they should also use fullInstructions instead of baseInstructions

  // Default return for other package types
  return fullInstructions;
}

/**
 * Generate AI-based project code using OpenAI API
 */
export async function generateProjectCode(config) {
  console.log(`🎨 Generating AI website for: ${config.name}`);
  console.log(`📦 Package type: ${config.packageType || config.category}`);

  if (!process.env.OPENAI_API_KEY) {
    console.warn("⚠️ Missing OPENAI_API_KEY — returning default fallback code.");
    return `
      // App.jsx
      import React from 'react';
      export default function App() {
        return (
          <div style={{ textAlign: "center", padding: "2rem" }}>
            <h1>${config.name}</h1>
            <p>${config.description}</p>
            <p><em>AI generation unavailable (no API key detected)</em></p>
          </div>
        );
      }
    `;
  }

  const Anthropic = (await import("@anthropic-ai/sdk")).default;
  const anthropic = new Anthropic({ apiKey: process.env.OPENAI_API_KEY });
  const prompt = generatePromptByPackage(config);

  const MAX_RETRIES = 5;

  for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
    try {
      console.log(`🔄 AI generation attempt ${attempt}/${MAX_RETRIES}`);

      const response = await anthropic.messages.create({
        model: "claude-sonnet-4-20250514",
        max_tokens: 20000,
        messages: [
          {
            role: "user",
            content: prompt
          }
        ],
        system: `You are an expert React and Vite developer. You MUST follow these rules EXACTLY:

1. Format ALL code blocks as: \`\`\`language:filename

2. EVERY component file (Shop.jsx, Cart.jsx, Checkout.jsx, Login.jsx, etc.) MUST end with EXACTLY these two lines:
   }
   export default ComponentName;

3. NEVER use these formats:
   - export default function ComponentName() { }
   - export { ComponentName }
   - const ComponentName = () => { }; export default ComponentName;

4. Context files (CartContext.jsx) MUST use:
   - export const ProviderName
   - export const useHookName

5. ALL imports MUST include .jsx extension

6. CRITICAL: DO NOT create or import AdminDashboard.jsx or any admin features
   - App.jsx should ONLY route to: Home, Shop, Cart, Checkout
   - Do NOT add /admin route
   - Do NOT create admin panel or dashboard

7. Only generate files that are explicitly needed and referenced

EXAMPLE - This is the ONLY acceptable format for components:
\`\`\`jsx:src/components/Navbar.jsx
import { Link } from 'react-router-dom';

function Navbar() {
  return <nav>Navigation</nav>;
}

export default Navbar;
\`\`\`

CRITICAL: Every single component file MUST have "export default ComponentName" as the last line.
Do NOT create any admin features, dashboards, or management panels.
Do NOT deviate from these export patterns under any circumstances.`,
        temperature: 0.3,
      });

      const generatedCode = response.content[0]?.text?.trim();
      if (!generatedCode) throw new Error("Empty AI response");

      console.log("✅ AI code generated successfully");
      return generatedCode;

    } catch (err) {
      const errorMsg = err.message?.toLowerCase() || '';

      // Check if it's a retryable error (overload/rate limit)
      if (errorMsg.includes('overloaded') || errorMsg.includes('529') || errorMsg.includes('rate')) {
        if (attempt < MAX_RETRIES) {
          const delay = 1000 * Math.pow(2, attempt); // Exponential backoff: 2s, 4s, 8s, 16s
          console.warn(`⏳ API overloaded (attempt ${attempt}/${MAX_RETRIES}). Waiting ${delay}ms before retry...`);
          await new Promise(resolve => setTimeout(resolve, delay));
          continue; // Retry
        }
      }

      // Non-retryable error or max retries reached
      console.error(`❌ Error generating project code (attempt ${attempt}/${MAX_RETRIES}):`, err.message);

      if (attempt === MAX_RETRIES) {
        console.error("❌ Max retries reached. Returning fallback code.");
        return `
          // App.jsx
          import React from 'react';
          export default function App() {
            return (
              <div style={{ textAlign: "center", padding: "2rem" }}>
                <h1>${config.name}</h1>
                <p>${config.description}</p>
                <p><em>AI generation failed after ${MAX_RETRIES} attempts: ${err.message}</em></p>
              </div>
            );
          }
        `;
      }
    }
  }
}